# Generated by Django 5.1.1 on 2024-11-13 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerId', models.CharField(db_index=True, max_length=50, unique=True)),
                ('playerName', models.CharField(blank=True, db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerspectiveAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField(blank=True)),
                ('severe_toxicity', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('sexually_explicit', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('threat', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('profanity', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('toxicity', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('identity_attack', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('insult', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('language', models.CharField(blank=True, db_index=True, max_length=5)),
                ('detected_language', models.CharField(blank=True, db_index=True, max_length=5)),
                ('chat_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_perspective_analysis', to='equalizer.chatmessage')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_chat_message', to='equalizer.player'),
        ),
    ]
