# Generated by Django 5.1.1 on 2024-11-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equalizer', '0002_session_chatmessage_assigned_tox_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWordShortForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=255, unique=True)),
                ('full_form', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
