# Generated by Django 5.1.1 on 2024-11-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equalizer', '0004_badwordshortform_real_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badwordshortform',
            name='real_form',
        ),
    ]
