# Generated by Django 5.1.5 on 2025-01-28 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equalizer', '0007_chatmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='toxicityincident',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_toxicity_incident', to='equalizer.session'),
        ),
        migrations.AlterField(
            model_name='toxicityincident',
            name='sessionId',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
