# Generated by Django 5.1.5 on 2025-02-16 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equalizer', '0010_player_user_session_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerId',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='sessionId',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'playerId')},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('user', 'sessionId')},
        ),
    ]
