# Generated by Django 5.1.5 on 2025-01-28 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_rest_key', to='rest_framework_api_key.apikey')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_api_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
